.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. iridium_qt test_iridium_qt
clean: FORCE
	$(MAKE) -C .. iridium_qt_clean test_iridium_qt_clean
check: FORCE
	$(MAKE) -C .. test_iridium_qt_check
iridium-qt iridium-qt.exe: FORCE
	 $(MAKE) -C .. iridium_qt
